### ISSUE TITLE
Can't install with cabal on Ubuntu 15.04

### ISSUE THREAD

**Issue by ethanwhite** [PhDP/Akarui#4]
I was trying to experiment with this package while reading your excellent blog post on Markov logic networks. This is my first time doing anything with Haskell so this is likely just me not understanding something.

When I go to follow the install instructions I get an error based on the required `cabal` version:

```
ethan@stice:~/Manticore (master)$ cabal update
Downloading the latest package list from hackage.haskell.org
ethan@stice:~/Manticore (master)$ cabal install
Resolving dependencies...
Configuring Manticore-0.1.0.0...
Failed to install Manticore-0.1.0.0
Build log ( /home/ethan/.cabal/logs/Manticore-0.1.0.0.log ):
cabal: Error: some packages failed to install:
Manticore-0.1.0.0 failed during the configure step. The exception was:
user error (The package 'Manticore' requires Cabal library version -any &&
>=1.18 but no suitable version is installed.)
ethan@stice:~/Manticore (master)$ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library 
```

Any help would be appreciated.

**Comment by PhDP** [comment]
Try to install libcabal via Ubuntu's package manager:

```
$ sudo apt-get install libghc-cabal-dev
```

I'm also on 15.04 and I suspect I don't have this issue because this package is installed.

**Comment by ethanwhite** [comment]
Yep, that took care of it. Thanks!

**Comment by PhDP** [comment]
Thanks for noting this, I'll add a note in INSTALL.md.
