### ISSUE TITLE
Error on 2nd call of ML.ask when following tutorial in blog post

### ISSUE THREAD

**Issue by ethanwhite** [PhDP/Akarui#5]
When following the walk through at:
http://phdp.github.io/posts/2015-07-13-srl-code.html

I get the following error when I execute `ghci> let ask' = ML.ask mln' cs`:

```
Prelude> import qualified Manticore.MarkovLogic as ML
Prelude ML> let mln = ML.fromStrings ["∀x Smoking(x) ⇒ Cancer(x) 1.5", "∀x∀y Friend(x, y) ∧ Smoking(x) ⇒ Smoking(y) 1.1"]
...
Prelude ML> let cs = ["Elaine", "George", "Jerry"]
Prelude ML> let ask = ML.ask mln cs
Prelude ML> let mln' = ML.tell "2.0 A.x,y,z Friend(x, y) and Friend(y, z) => Friend(x, z)" mln
Prelude ML> let ask' = ML.ask mln' cs

<interactive>:7:12:
    Failed to load interface for `ML'
    Use -v to see a list of the files searched for.
```

**Comment by PhDP** [comment]
Yes, I fixed this (and warned you on twitter) _before_ you submitted this issue :P

It's just a quirk with cabal (it has many more quirks) and qualified imports. I replaced the qualified import by "import Manticore.MarkovLogic" in the post to avoid this issue.

**Comment by ethanwhite** [comment]
Thanks! I'm avoiding twitter in mornings at the moment so I can do things like focus on learning about Markov logic networks :).
